version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:14
    container_name: postgres_container
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 78124770
      POSTGRES_DB: petmanager
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./server
    container_name: backend_container
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:78124770@db:5432/petmanager"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: ["sh", "-c", "npx prisma migrate deploy && npm run dev"]

volumes:
  pgdata:
